add_newline = false
prompt_order = [
  "directory",
  "git_branch",
  "git_commit",
  "git_state",
  "git_status",
  "golang",
  "nodejs",
  "java",
  "python",
  "ruby",
  "rust",
  "crystal",
  "line_break",
  "character"
]

[character]
symbol = "â–¶"
style_success = "white"

[line_break]
disabled = false

[directory]
disabled = false
prefix = ""
truncate_to_repo = false
style = "bold fg:#94bdff"

[git_status]
prefix = "("
suffix = ") "
modified = " !"
untracked = "?"

[git_branch]
style = "bold green"
prefix = ""

# Language Support
[golang]
symbol = "ğŸ­ "
style = "bold cyan"

[ruby]
symbol = "ğŸ¦€ "
style = "bold red"

[java]
symbol = "ğŸŒŸ "
style = "bold yellow"

[crystal]
style = "bold blue"