# Port of Oh My Zsh theme "avit" to Starship.
# ======
# 
# Supports: Java, Node.JS, PHP, Go, Crystal, Python, Ruby, and Rust modules
# Other modules include: Directory, Git Branch/Commit/State/Status, and Docker

add_newline = false
format = """\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $docker_context\
  $crystal\
  $golang\
  $java\
  $nodejs\
  $php\
  $python\
  $ruby\
  $rust\
  $line_break\
  $character
"""

[character]
success_symbol = "[â–¶]($bold white)"
error_symbol = "[â–¶](bold red)"

[directory]
disabled = false
format = "[$path](bold fg:#94bdff) "
truncate_to_repo = false

[git_status]
format = "([$all_status$ahead_behind](bold fg:#94bdff) )"
all_status = "$conflicted $stashed $deleted $renamed $modified $staged $untracked"
staged = "âœš "
modified = "âš‘ "
untracked = "â—’ "
deleted = "âœ– "
renamed = "â–´ "

[git_branch]
format = "on [î‚  $branch](bold green) "

# Language Support
[docker_context]
format = "via [ïŒˆ $context](bold cyan) "
disabled = false

[crystal]
format = "via [ğŸ”® $version](bold blue) "

[golang]
format = "via [î˜§ $version](bold cyan) "

[java]
format = "via [î‰– $version](bold yellow) "

[nodejs]
format = "via [î‰ $version](bold green) "

[php]
format = "via [î˜ˆ $version](bold cyan) "

[python]
format = "via [î˜† $version](bold blue) "

[ruby]
format = "via [îˆ¾ $version](bold red) "

[rust]
format = "via [ï€“ $version](bold red) "

# Broken: Docker