add_newline = false
prompt_order = [
  "directory",
  "git_branch",
  "git_commit",
  "git_state",
  "git_status",
  "golang",
  "nodejs",
  "java",
  "python",
  "ruby",
  "rust",
  "crystal",
  "line_break",
  "character"
]

[character]
symbol = "â–¶"
style_success = "white"

[directory]
disabled = false
prefix = ""
truncate_to_repo = false
style = "bold fg:#94bdff"

[git_status]
# avit prompt icons:
# dirty      = " âœ—"
# clean      = " âœ”"
# added      = "âœš "
# modified   = "âš‘ "
# deleted    = "âœ– "
# renamed    = "â–´ "
# unmerged   = "Â§ "
# untracked  = "â—’ "
prefix = ""
suffix = " "
modified = "âš‘"
untracked = " â—’"
deleted = "âœ– "
renamed = "â–´ "
style = "bold fg:#94bdff"

[git_branch]
style = "bold green"
prefix = ""

# Language Support
[golang]
symbol = "ğŸ­ "
style = "bold cyan"

[ruby]
symbol = "ğŸ¦€ "
style = "bold red"

[java]
symbol = "ğŸŒŸ "
style = "bold yellow"

[crystal]
style = "bold blue"